# Generated by Django 5.0.4 on 2024-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='_old_password',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
