version: '3.12.1'

networks:
  meeting_net:
    driver: bridge

services:
  meeting_calendar:
    build: .
    volumes:
      - ${HOME}/meeting-calender/db.sqlite3:/django/db.sqlite3
      - .:/django
    env_file:
      - path: .env
        required: true
    ports:
      - 8004:8000
    image: meeting_calendar:django
    container_name: meeting_calendar
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

    networks:
      - meeting_net
