# Generated by Django 5.0.4 on 2024-04-25 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='display_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date to display the news'),
        ),
    ]
