# Generated by Django 5.0.4 on 2024-04-19 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Give a title to the session', max_length=255, verbose_name='Session title')),
                ('start', models.DateTimeField(help_text='When does this session start?', verbose_name='Starts')),
                ('end', models.DateTimeField(help_text='When does this session end?', verbose_name='Ends')),
                ('is_pending', models.BooleanField(default=True, help_text='Has this session been held? If so, uncheck this.')),
                ('cancelled', models.BooleanField(default=False, help_text='Check this if you want to cancel this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='UnavailablePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(help_text='From what date and time you will be unavailable?', verbose_name='From')),
                ('end', models.DateTimeField(help_text='Till what date and time you will be unavailable?', verbose_name='To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unavailable Period',
                'verbose_name_plural': 'Unavailable Periods',
                'ordering': ['start'],
            },
        ),
    ]
