# Generated by Django 5.0.4 on 2024-04-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='unavailableperiod',
            options={'ordering': ['start'], 'verbose_name': 'Unavailable Period', 'verbose_name_plural': 'Unavailable Periods'},
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
