# Generated by Django 5.0.4 on 2024-04-27 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booked_by',
            field=models.ForeignKey(help_text='Who booked this session?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booked by'),
        ),
        migrations.AddField(
            model_name='session',
            name='link',
            field=models.ForeignKey(blank=True, help_text='The link to the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='links.link', verbose_name='Link'),
        ),
    ]
