# Generated by Django 5.0.4 on 2024-04-17 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_session_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='Has this session been held? If so, uncheck this.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='booked_by',
            field=models.ForeignKey(help_text='Who booked this session?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booked by'),
        ),
        migrations.AlterField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Check this if you want to cancel this session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(help_text='When does this session end?', verbose_name='Ends'),
        ),
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.URLField(blank=True, help_text='Provide a link to the session if any', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(help_text='When does this session start?', verbose_name='Starts'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(help_text='Give a title to the session', max_length=255, verbose_name='Session title'),
        ),
        migrations.AlterField(
            model_name='unavailableperiod',
            name='end',
            field=models.DateTimeField(help_text='Till what date and time you will be unavailable?', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='unavailableperiod',
            name='start',
            field=models.DateTimeField(help_text='From what date and time you will be unavailable?', verbose_name='From'),
        ),
    ]
