# Generated by Django 5.0.4 on 2024-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_session_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='session',
            name='has_held',
            field=models.BooleanField(default=False, help_text='Has this session been held? If so, uncheck this.'),
        ),
    ]
