# Generated by Django 5.0.4 on 2024-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_session_is_pending_session_has_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='has_held',
            field=models.BooleanField(default=False, help_text='Has this session been held? If so, check this.'),
        ),
    ]
