# Generated by Django 5.0.4 on 2024-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_session_has_held'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start__date', 'start__time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='session',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='When was this session date or time changed?', null=True, verbose_name='Rescheduled at'),
        ),
    ]
